version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=the_boring_todo_list_1
      - POSTGRES_USER=boring
      - POSTGRES_PASSWORD=todo
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      # - ../db/seeds.sql:/docker-entrypoint-initdb.d/2_seeds.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data: