services:
  postgres:
    image: docker.io/postgres:17
    environment:
      - POSTGRES_USER=boring
      - POSTGRES_PASSWORD=todo
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ../db/2_seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

volumes:
  postgres_data:
