#!/usr/bin/env bash
SCRIPT_PATH=${0%/*}
PROJECT_PATH=$SCRIPT_PATH/..

go install github.com/vektra/mockery/v2@latest
rm -R $PROJECT_PATH/mocks

# INTERNAL #
mockery --all --case underscore --packageprefix mock_ --keeptree --with-expecter \
  --dir $PROJECT_PATH/internal \
  --output $PROJECT_PATH/mocks

# PKG #
rm -r $PROJECT_PATH/pkg/gorm_provider/mocks
mockery --name AbstractRepository --case underscore --packageprefix mock_ --keeptree --with-expecter \
  --dir $PROJECT_PATH/pkg/gorm_provider --output $PROJECT_PATH/pkg/gorm_provider/mocks
