#!/usr/bin/env bash
set -eo pipefail
SCRIPT_DIR=${0%/*}

# Set default ENV_PATH
if [[ -z $ENV_PATH ]]; then
  ENV_PATH="${SCRIPT_DIR}/../secrets/.env"
fi

# Load .env
if [[ -e $ENV_PATH ]]; then
  export $(cat $ENV_PATH | xargs)
else
  echo "Missing .env file"
  exit 1
fi

PGPASSWORD=$DB_PASSWORD pg_dump -d $DB_NAME -h $DB_HOST -p $DB_PORT -U $DB_USER --schema-only > db/1_schema.sql