#!/usr/bin/env bash
set -eo pipefail
DIR=${0%/*}

declare -A ARG_MAP
for ARG in "$@"; do
  ARG_MAP[$ARG]=1
done

trap handle_ctrl_c INT
function handle_ctrl_c() {
  docker compose -f "${DIR}/docker-compose.yml" stop
}

(docker compose -f "${DIR}/docker-compose.yml" up)&

go install github.com/joho/godotenv/cmd/godotenv@latest
go install github.com/cosmtrek/air@latest

if [[ ! ${ARG_MAP["--skip-app"]} ]]; then
  godotenv air -build.cmd "go build -o tmp/main ./cmd/app"
else
  sleep infinity
fi