#!/usr/bin/env bash
set -eo pipefail
DIR=${0%/*}

declare -A ARG_MAP
for ARG in "$@"; do
  ARG_MAP[$ARG]=1
done

trap handle_ctrl_c INT
function handle_ctrl_c() {
  docker compose --project-name the-boring-todo-list-1 -f "${DIR}/docker-compose.yml" stop
}

(docker compose --project-name the-boring-todo-list-1 -f "${DIR}/docker-compose.yml" up)&

if [[ ! ${ARG_MAP["--skip-app"]} ]]; then
  go install github.com/joho/godotenv/cmd/godotenv@latest
  go install github.com/cosmtrek/air@latest
  godotenv air -build.cmd "go build -o tmp/main ./cmd/app"
else
  sleep infinity
fi