#!/usr/bin/env bash
set -eo pipefail

SCRIPT_PATH=${0%/*}
PROJECT_PATH=$SCRIPT_PATH/..
CONTAINER_NAME='the_boring_todo_list_1_test'

docker run --detach --name $CONTAINER_NAME \
  -e POSTGRES_DB=the_boring_todo_list_1 \
  -e POSTGRES_USER=boring \
  -e POSTGRES_PASSWORD=todo \
  --health-cmd 'pg_isready' \
  --health-interval '1s' \
  -p 5433:5432 \
  postgres:14 > /dev/null

clean_up () {
  docker stop $CONTAINER_NAME > /dev/null
  docker rm $CONTAINER_NAME > /dev/null
} 
trap clean_up EXIT

export DB_PORT=5433

echo 'Waiting for database to be ready'
while [[ $(docker inspect -f '{{.State.Health.Status}}' $CONTAINER_NAME) == 'healthy' ]]; do :; done

go clean -testcache
go test --cover $PROJECT_PATH/...