// Code generated by mockery v2.33.3. DO NOT EDIT.

package mock_gorm_provider

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// AbstractProvider is an autogenerated mock type for the AbstractProvider type
type AbstractProvider struct {
	mock.Mock
}

type AbstractProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *AbstractProvider) EXPECT() *AbstractProvider_Expecter {
	return &AbstractProvider_Expecter{mock: &_m.Mock}
}

// GetDBFromContext provides a mock function with given fields: ctx
func (_m *AbstractProvider) GetDBFromContext(ctx context.Context) *gorm.DB {
	ret := _m.Called(ctx)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// AbstractProvider_GetDBFromContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDBFromContext'
type AbstractProvider_GetDBFromContext_Call struct {
	*mock.Call
}

// GetDBFromContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AbstractProvider_Expecter) GetDBFromContext(ctx interface{}) *AbstractProvider_GetDBFromContext_Call {
	return &AbstractProvider_GetDBFromContext_Call{Call: _e.mock.On("GetDBFromContext", ctx)}
}

func (_c *AbstractProvider_GetDBFromContext_Call) Run(run func(ctx context.Context)) *AbstractProvider_GetDBFromContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AbstractProvider_GetDBFromContext_Call) Return(_a0 *gorm.DB) *AbstractProvider_GetDBFromContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AbstractProvider_GetDBFromContext_Call) RunAndReturn(run func(context.Context) *gorm.DB) *AbstractProvider_GetDBFromContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransaction provides a mock function with given fields: ctx, fc
func (_m *AbstractProvider) NewTransaction(ctx context.Context, fc func(context.Context) error) error {
	ret := _m.Called(ctx, fc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AbstractProvider_NewTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTransaction'
type AbstractProvider_NewTransaction_Call struct {
	*mock.Call
}

// NewTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fc func(context.Context) error
func (_e *AbstractProvider_Expecter) NewTransaction(ctx interface{}, fc interface{}) *AbstractProvider_NewTransaction_Call {
	return &AbstractProvider_NewTransaction_Call{Call: _e.mock.On("NewTransaction", ctx, fc)}
}

func (_c *AbstractProvider_NewTransaction_Call) Run(run func(ctx context.Context, fc func(context.Context) error)) *AbstractProvider_NewTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *AbstractProvider_NewTransaction_Call) Return(_a0 error) *AbstractProvider_NewTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AbstractProvider_NewTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *AbstractProvider_NewTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewAbstractProvider creates a new instance of AbstractProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAbstractProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *AbstractProvider {
	mock := &AbstractProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
