// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AbstractEntity is an autogenerated mock type for the AbstractEntity type
type AbstractEntity struct {
	mock.Mock
}

// GetTableName provides a mock function with given fields:
func (_m *AbstractEntity) GetTableName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ToMap provides a mock function with given fields:
func (_m *AbstractEntity) ToMap() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

type mockConstructorTestingTNewAbstractEntity interface {
	mock.TestingT
	Cleanup(func())
}

// NewAbstractEntity creates a new instance of AbstractEntity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAbstractEntity(t mockConstructorTestingTNewAbstractEntity) *AbstractEntity {
	mock := &AbstractEntity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
