// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// QueryOption is an autogenerated mock type for the QueryOption type
type QueryOption struct {
	mock.Mock
}

// Apply provides a mock function with given fields: _a0
func (_m *QueryOption) Apply(_a0 *gorm.DB) *gorm.DB {
	ret := _m.Called(_a0)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

type mockConstructorTestingTNewQueryOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueryOption creates a new instance of QueryOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueryOption(t mockConstructorTestingTNewQueryOption) *QueryOption {
	mock := &QueryOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
