// Code generated by mockery v2.36.1. DO NOT EDIT.

package mock_repository

import (
	context "context"

	entity "example.com/the-boring-to-do-list-1/internal/entity"
	gorm_provider "example.com/the-boring-to-do-list-1/pkg/gorm_provider"

	mock "github.com/stretchr/testify/mock"
)

// AbstractUserRepository is an autogenerated mock type for the AbstractUserRepository type
type AbstractUserRepository struct {
	mock.Mock
}

type AbstractUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AbstractUserRepository) EXPECT() *AbstractUserRepository_Expecter {
	return &AbstractUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, record, opts
func (_m *AbstractUserRepository) Create(ctx context.Context, record *entity.User, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, record)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, ...interface{}) error); ok {
		r0 = rf(ctx, record, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AbstractUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AbstractUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - record *entity.User
//   - opts ...interface{}
func (_e *AbstractUserRepository_Expecter) Create(ctx interface{}, record interface{}, opts ...interface{}) *AbstractUserRepository_Create_Call {
	return &AbstractUserRepository_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, record}, opts...)...)}
}

func (_c *AbstractUserRepository_Create_Call) Run(run func(ctx context.Context, record *entity.User, opts ...interface{})) *AbstractUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(*entity.User), variadicArgs...)
	})
	return _c
}

func (_c *AbstractUserRepository_Create_Call) Return(_a0 error) *AbstractUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AbstractUserRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.User, ...interface{}) error) *AbstractUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, opts
func (_m *AbstractUserRepository) Delete(ctx context.Context, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) error); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AbstractUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AbstractUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...interface{}
func (_e *AbstractUserRepository_Expecter) Delete(ctx interface{}, opts ...interface{}) *AbstractUserRepository_Delete_Call {
	return &AbstractUserRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AbstractUserRepository_Delete_Call) Run(run func(ctx context.Context, opts ...interface{})) *AbstractUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AbstractUserRepository_Delete_Call) Return(_a0 error) *AbstractUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AbstractUserRepository_Delete_Call) RunAndReturn(run func(context.Context, ...interface{}) error) *AbstractUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, opts
func (_m *AbstractUserRepository) Find(ctx context.Context, opts ...interface{}) ([]entity.User, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) ([]entity.User, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) []entity.User); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AbstractUserRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type AbstractUserRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...interface{}
func (_e *AbstractUserRepository_Expecter) Find(ctx interface{}, opts ...interface{}) *AbstractUserRepository_Find_Call {
	return &AbstractUserRepository_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AbstractUserRepository_Find_Call) Run(run func(ctx context.Context, opts ...interface{})) *AbstractUserRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AbstractUserRepository_Find_Call) Return(_a0 []entity.User, _a1 error) *AbstractUserRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AbstractUserRepository_Find_Call) RunAndReturn(run func(context.Context, ...interface{}) ([]entity.User, error)) *AbstractUserRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindInBatches provides a mock function with given fields: ctx, bacthSize, fn, opts
func (_m *AbstractUserRepository) FindInBatches(ctx context.Context, bacthSize int, fn func([]entity.User) error, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, bacthSize, fn)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, func([]entity.User) error, ...interface{}) error); ok {
		r0 = rf(ctx, bacthSize, fn, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AbstractUserRepository_FindInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindInBatches'
type AbstractUserRepository_FindInBatches_Call struct {
	*mock.Call
}

// FindInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - bacthSize int
//   - fn func([]entity.User) error
//   - opts ...interface{}
func (_e *AbstractUserRepository_Expecter) FindInBatches(ctx interface{}, bacthSize interface{}, fn interface{}, opts ...interface{}) *AbstractUserRepository_FindInBatches_Call {
	return &AbstractUserRepository_FindInBatches_Call{Call: _e.mock.On("FindInBatches",
		append([]interface{}{ctx, bacthSize, fn}, opts...)...)}
}

func (_c *AbstractUserRepository_FindInBatches_Call) Run(run func(ctx context.Context, bacthSize int, fn func([]entity.User) error, opts ...interface{})) *AbstractUserRepository_FindInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(int), args[2].(func([]entity.User) error), variadicArgs...)
	})
	return _c
}

func (_c *AbstractUserRepository_FindInBatches_Call) Return(_a0 error) *AbstractUserRepository_FindInBatches_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AbstractUserRepository_FindInBatches_Call) RunAndReturn(run func(context.Context, int, func([]entity.User) error, ...interface{}) error) *AbstractUserRepository_FindInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: ctx, opts
func (_m *AbstractUserRepository) FindOne(ctx context.Context, opts ...interface{}) (entity.User, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (entity.User, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) entity.User); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AbstractUserRepository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type AbstractUserRepository_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...interface{}
func (_e *AbstractUserRepository_Expecter) FindOne(ctx interface{}, opts ...interface{}) *AbstractUserRepository_FindOne_Call {
	return &AbstractUserRepository_FindOne_Call{Call: _e.mock.On("FindOne",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AbstractUserRepository_FindOne_Call) Run(run func(ctx context.Context, opts ...interface{})) *AbstractUserRepository_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AbstractUserRepository_FindOne_Call) Return(_a0 entity.User, _a1 error) *AbstractUserRepository_FindOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AbstractUserRepository_FindOne_Call) RunAndReturn(run func(context.Context, ...interface{}) (entity.User, error)) *AbstractUserRepository_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// First provides a mock function with given fields: ctx, opts
func (_m *AbstractUserRepository) First(ctx context.Context, opts ...interface{}) (entity.User, bool, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 entity.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) (entity.User, bool, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) entity.User); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...interface{}) bool); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, ...interface{}) error); ok {
		r2 = rf(ctx, opts...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AbstractUserRepository_First_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'First'
type AbstractUserRepository_First_Call struct {
	*mock.Call
}

// First is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...interface{}
func (_e *AbstractUserRepository_Expecter) First(ctx interface{}, opts ...interface{}) *AbstractUserRepository_First_Call {
	return &AbstractUserRepository_First_Call{Call: _e.mock.On("First",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AbstractUserRepository_First_Call) Run(run func(ctx context.Context, opts ...interface{})) *AbstractUserRepository_First_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AbstractUserRepository_First_Call) Return(_a0 entity.User, _a1 bool, _a2 error) *AbstractUserRepository_First_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AbstractUserRepository_First_Call) RunAndReturn(run func(context.Context, ...interface{}) (entity.User, bool, error)) *AbstractUserRepository_First_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuery provides a mock function with given fields: ctx, opts
func (_m *AbstractUserRepository) NewQuery(ctx context.Context, opts ...interface{}) gorm_provider.Query[entity.User] {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 gorm_provider.Query[entity.User]
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) gorm_provider.Query[entity.User]); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Get(0).(gorm_provider.Query[entity.User])
	}

	return r0
}

// AbstractUserRepository_NewQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewQuery'
type AbstractUserRepository_NewQuery_Call struct {
	*mock.Call
}

// NewQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...interface{}
func (_e *AbstractUserRepository_Expecter) NewQuery(ctx interface{}, opts ...interface{}) *AbstractUserRepository_NewQuery_Call {
	return &AbstractUserRepository_NewQuery_Call{Call: _e.mock.On("NewQuery",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AbstractUserRepository_NewQuery_Call) Run(run func(ctx context.Context, opts ...interface{})) *AbstractUserRepository_NewQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AbstractUserRepository_NewQuery_Call) Return(_a0 gorm_provider.Query[entity.User]) *AbstractUserRepository_NewQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AbstractUserRepository_NewQuery_Call) RunAndReturn(run func(context.Context, ...interface{}) gorm_provider.Query[entity.User]) *AbstractUserRepository_NewQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransaction provides a mock function with given fields: ctx, fc
func (_m *AbstractUserRepository) NewTransaction(ctx context.Context, fc func(context.Context) error) error {
	ret := _m.Called(ctx, fc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AbstractUserRepository_NewTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTransaction'
type AbstractUserRepository_NewTransaction_Call struct {
	*mock.Call
}

// NewTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fc func(context.Context) error
func (_e *AbstractUserRepository_Expecter) NewTransaction(ctx interface{}, fc interface{}) *AbstractUserRepository_NewTransaction_Call {
	return &AbstractUserRepository_NewTransaction_Call{Call: _e.mock.On("NewTransaction", ctx, fc)}
}

func (_c *AbstractUserRepository_NewTransaction_Call) Run(run func(ctx context.Context, fc func(context.Context) error)) *AbstractUserRepository_NewTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *AbstractUserRepository_NewTransaction_Call) Return(_a0 error) *AbstractUserRepository_NewTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AbstractUserRepository_NewTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *AbstractUserRepository_NewTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, update, opts
func (_m *AbstractUserRepository) Update(ctx context.Context, update interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, update)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...interface{}) error); ok {
		r0 = rf(ctx, update, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AbstractUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AbstractUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - update interface{}
//   - opts ...interface{}
func (_e *AbstractUserRepository_Expecter) Update(ctx interface{}, update interface{}, opts ...interface{}) *AbstractUserRepository_Update_Call {
	return &AbstractUserRepository_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, update}, opts...)...)}
}

func (_c *AbstractUserRepository_Update_Call) Run(run func(ctx context.Context, update interface{}, opts ...interface{})) *AbstractUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *AbstractUserRepository_Update_Call) Return(_a0 error) *AbstractUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AbstractUserRepository_Update_Call) RunAndReturn(run func(context.Context, interface{}, ...interface{}) error) *AbstractUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewAbstractUserRepository creates a new instance of AbstractUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAbstractUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AbstractUserRepository {
	mock := &AbstractUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
